import {
  StatusBarProps,
  StatusBarPropsAndroid,
  StatusBarPropsIOS,
  StyleProp,
  TextProps,
  TextStyle,
} from 'react-native';

import Text from './Text';
import FocusAwareStatusBar from './FocusAwareStatusBar';
import Icon from './Icon';
import {Button} from './Button';
export * from './ButtonGroup';

export type TFontSizes =
  | 'xs2'
  | 'xs'
  | 'sm'
  | 'base'
  | 'lg'
  | 'xl'
  | 'xl2'
  | 'xl3'
  | 'xl4'
  | 'xl5'
  | number;

export interface IText extends TextProps {
  children?: React.ReactNode;
  text?: string;
  size?: TFontSizes;
  variant?: 'light' | 'normal' | 'semibold' | 'bold';
  style?: StyleProp<TextStyle>;
  color?: string;
}

export type IStatusBarProps = StatusBarProps &
  StatusBarPropsAndroid &
  StatusBarPropsIOS;

// declare type iconname list here
export type IconName =
  | 'activity'
  | 'airplay'
  | 'alert-circle'
  | 'alert-octagon'
  | 'alert-triangle'
  | 'align-center'
  | 'align-justify'
  | 'align-left'
  | 'align-right'
  | 'anchor'
  | 'aperture'
  | 'archive'
  | 'arrow-down'
  | 'arrow-down-circle'
  | 'arrow-down-left'
  | 'arrow-down-outline'
  | 'arrow-down-right'
  | 'arrow-left'
  | 'arrow-left-circle'
  | 'arrow-right'
  | 'arrow-right-circle'
  | 'arrow-up'
  | 'arrow-up-circle'
  | 'arrow-up-left'
  | 'arrow-up-outline'
  | 'arrow-up-right'
  | 'at-sign'
  | 'award'
  | 'bank'
  | 'bar-chart'
  | 'bar-chart-2'
  | 'bar-chart-3'
  | 'battery'
  | 'battery-charging'
  | 'bell'
  | 'bell-off'
  | 'bluetooth'
  | 'bold'
  | 'book'
  | 'book-2'
  | 'book-open'
  | 'bookmark'
  | 'bookmark-filled'
  | 'box'
  | 'box1'
  | 'briefcase'
  | 'building'
  | 'calendar'
  | 'camera'
  | 'camera-off'
  | 'cast'
  | 'chat'
  | 'chat-bubble'
  | 'chat-bubble-round'
  | 'chat-outline'
  | 'check'
  | 'check-circle'
  | 'check-circle-filled'
  | 'check-square'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'chevrons-down'
  | 'chevrons-left'
  | 'chevrons-right'
  | 'chevrons-up'
  | 'chrome'
  | 'circle'
  | 'clipboard'
  | 'clock'
  | 'clock-2'
  | 'clock-3'
  | 'cloud'
  | 'cloud-drizzle'
  | 'cloud-lightning'
  | 'cloud-off'
  | 'cloud-rain'
  | 'cloud-snow'
  | 'code'
  | 'codepen'
  | 'coffee'
  | 'coins'
  | 'command'
  | 'compass'
  | 'compass-filled'
  | 'copy'
  | 'copy-2'
  | 'corner-down-left'
  | 'corner-down-right'
  | 'corner-left-down'
  | 'corner-left-up'
  | 'corner-right-down'
  | 'corner-right-up'
  | 'corner-up-left'
  | 'corner-up-right'
  | 'cpu'
  | 'credit-card'
  | 'crop'
  | 'crosshair'
  | 'crown'
  | 'database'
  | 'delete'
  | 'disc'
  | 'dollar-sign'
  | 'dot'
  | 'dots'
  | 'down-triangle'
  | 'download'
  | 'download-cloud'
  | 'droplet'
  | 'edit'
  | 'edit-2'
  | 'edit-3'
  | 'euro'
  | 'external-link'
  | 'eye'
  | 'eye-off'
  | 'face-id'
  | 'facebook'
  | 'fast-forward'
  | 'feather'
  | 'file'
  | 'file-minus'
  | 'file-plus'
  | 'file-text'
  | 'film'
  | 'filter'
  | 'fingerprint'
  | 'flag'
  | 'folder'
  | 'folder-minus'
  | 'folder-plus'
  | 'frown'
  | 'gif-box-outline'
  | 'gift'
  | 'git-branch'
  | 'git-commit'
  | 'git-merge'
  | 'git-pull-request'
  | 'github'
  | 'gitlab'
  | 'globe'
  | 'grid'
  | 'hard-drive'
  | 'hash'
  | 'headphones'
  | 'heart'
  | 'help-circle'
  | 'history'
  | 'home'
  | 'image'
  | 'inbox'
  | 'info'
  | 'info-circle-filled'
  | 'instagram'
  | 'italic'
  | 'joystick'
  | 'key'
  | 'layers'
  | 'layout'
  | 'life-buoy'
  | 'link'
  | 'link-2'
  | 'link-3'
  | 'linkedin'
  | 'list'
  | 'loader'
  | 'lock'
  | 'log-in'
  | 'log-out'
  | 'mail'
  | 'map'
  | 'map-pin'
  | 'maximize'
  | 'maximize-2'
  | 'meh'
  | 'menu'
  | 'message-circle'
  | 'message-square'
  | 'mic'
  | 'mic-off'
  | 'minimize'
  | 'minimize-2'
  | 'minus'
  | 'minus-circle'
  | 'minus-square'
  | 'monitor'
  | 'moon'
  | 'more-horizontal'
  | 'more-vertical'
  | 'mouse-pointer'
  | 'move'
  | 'music'
  | 'navigation'
  | 'navigation-2'
  | 'notification-bell'
  | 'octagon'
  | 'package'
  | 'paperclip'
  | 'pause'
  | 'pause-circle'
  | 'pen-tool'
  | 'percent'
  | 'phone'
  | 'phone-call'
  | 'phone-forwarded'
  | 'phone-incoming'
  | 'phone-missed'
  | 'phone-off'
  | 'phone-outgoing'
  | 'phone-outline'
  | 'pie-chart'
  | 'pin-2'
  | 'pin-rotated'
  | 'play'
  | 'play-circle'
  | 'play-filled'
  | 'plus'
  | 'plus-circle'
  | 'plus-square'
  | 'pocket'
  | 'portofolio'
  | 'portofolio-filled'
  | 'power'
  | 'printer'
  | 'profile'
  | 'profile-outline'
  | 'radio'
  | 'radio-off'
  | 'radio-on'
  | 'radio-on-purple'
  | 'refresh-ccw'
  | 'refresh-cw'
  | 'repeat'
  | 'rewind'
  | 'rotate-ccw'
  | 'rotate-cw'
  | 'rss'
  | 'save'
  | 'scan-qr'
  | 'scissors'
  | 'search'
  | 'sections'
  | 'send'
  | 'server'
  | 'settings'
  | 'share'
  | 'share-2'
  | 'shield'
  | 'shield-off'
  | 'shopping-bag'
  | 'shopping-cart'
  | 'shuffle'
  | 'sidebar'
  | 'skip-back'
  | 'skip-forward'
  | 'slack'
  | 'slash'
  | 'sliders'
  | 'smartphone'
  | 'smile'
  | 'social'
  | 'speaker'
  | 'square'
  | 'star'
  | 'stop-circle'
  | 'sun'
  | 'sunrise'
  | 'sunset'
  | 'tablet'
  | 'tag'
  | 'target'
  | 'terminal'
  | 'text'
  | 'thermometer'
  | 'thumbs-down'
  | 'thumbs-up'
  | 'toggle-left'
  | 'toggle-right'
  | 'trash'
  | 'trash-2'
  | 'trello'
  | 'trending-down'
  | 'trending-up'
  | 'triangle'
  | 'truck'
  | 'tv'
  | 'twitter'
  | 'type'
  | 'umbrella'
  | 'underline'
  | 'unlock'
  | 'upload'
  | 'upload-cloud'
  | 'user'
  | 'user-check'
  | 'user-minus'
  | 'user-plus'
  | 'user-x'
  | 'users'
  | 'video'
  | 'video-off'
  | 'voicemail'
  | 'volume'
  | 'volume-1'
  | 'volume-2'
  | 'volume-x'
  | 'warning-triangle-filled'
  | 'watch'
  | 'wifi'
  | 'wifi-off'
  | 'wind'
  | 'x'
  | 'x-circle'
  | 'x-circle-filled'
  | 'x-square'
  | 'youtube'
  | 'zap'
  | 'zap-off'
  | 'zoom-in'
  | 'zoom-out';

export interface IconSet {
  icons: Array<any>;
}

export interface SvgIconProps {
  iconSet: IconSet;
  name: string;
  color?: string;
  size?: number;
  strokeWidth?: number;
  offset?: number; // some icon might have different padding, use this to offset it
  width?: number;
  height?: number;
  viewBoxWidthPercentage?: number;
  viewBoxHeightPercentage?: number;
}

export interface IconMap {
  name: string;
  paths: Array<string>;
  attrs?: Array<IconAttrs>;
}

interface IconAttrs {
  fill?: string;
}

export interface IIcon extends Omit<SvgIconProps, 'iconSet' | 'name' | 'size'> {
  name: IconName;
  color?: string;
  size?: TFontSizes;
  strokeWidth?: number;
  offset?: number;
}

export {FocusAwareStatusBar, Text, Icon, Button};
